# Generated by Django 5.2.7 on 2025-10-25 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('posttype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='posttype.posttype'),
        ),
    ]
