# Generated by Django 5.2.7 on 2025-10-30 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genders', '0001_initial'),
        ('gradeLevels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genders.gender')),
                ('gradeLevel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gradeLevels.gradelevel')),
                ('profile_user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
