# Generated by Django 5.2.7 on 2025-10-31 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalities', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='nationalities.nationality'),
            preserve_default=False,
        ),
    ]
