# Generated by Django 5.2.7 on 2025-11-01 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genders', '0001_initial'),
        ('gradeLevels', '0001_initial'),
        ('nationalities', '0001_initial'),
        ('profiles', '0002_profile_nationality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gender', to='genders.gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gradeLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gradeLevel', to='gradeLevels.gradelevel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nationality', to='nationalities.nationality'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
