# Generated by Django 5.2.7 on 2025-11-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_gender_alter_profile_gradelevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_roommate_post',
            field=models.BooleanField(default=False),
        ),
    ]
