# Generated by Django 5.2.7 on 2025-10-30 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('originalPostDateTime', models.DateTimeField(auto_now_add=True)),
                ('postLastUpdateDateTime', models.DateTimeField(auto_now=True)),
                ('funFact', models.TextField()),
                ('features', models.ManyToManyField(to='features.feature')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
