# Generated by Django 5.2.7 on 2025-10-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomatePost',
            new_name='RoommatePost',
        ),
    ]
