# Generated by Django 5.2.7 on 2025-11-01 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_gender_alter_profile_gradelevel_and_more'),
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bufferCount', models.IntegerField(default=0)),
                ('interestedProfiles', models.ManyToManyField(db_table='Interested_Roommates', related_name='interested_profiles', to='profiles.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.profile')),
            ],
        ),
    ]
