# Generated by Django 5.2.7 on 2025-10-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('roommates', '0002_rename_roomatepost_roommatepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepost',
            name='features',
            field=models.ManyToManyField(to='features.feature'),
        ),
    ]
