# Generated by Django 5.2.7 on 2025-11-04 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0002_interestedbuffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepost',
            name='budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='moveInDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
