# Generated by Django 5.2.7 on 2025-11-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0003_roommatepost_budget_roommatepost_moveindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommatepost',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
